# to run:  make -f Makefile run_unit
# example:  make -f Makefile clean

localization:
	@echo "╠ Generating the localization files..."
	@flutter gen-l10n
	@flutter pub get

clean:
	@echo "╠ Cleaning the project..."
	@rm -rf pubspec.lock
	@flutter clean
	@flutter pub get